# Generated by Django 2.2.6 on 2020-07-18 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('topic', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=30)),
                ('handled', models.IntegerField(default=0)),
                ('info', models.CharField(max_length=500)),
            ],
        ),
    ]
