# Generated by Django 2.2.6 on 2020-07-17 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('net', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=50)),
                ('device_name', models.CharField(max_length=50)),
                ('is_active', models.IntegerField(default=1)),
                ('status', models.IntegerField(choices=[(0, '离线'), (1, '在线')], default=0)),
                ('mac_addr', models.CharField(max_length=20)),
                ('Longitude', models.CharField(max_length=20)),
                ('Latitude', models.CharField(max_length=20)),
                ('info', models.CharField(max_length=200)),
                ('net', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='net.Net')),
            ],
        ),
    ]
